/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmSend: typeof import('./src/components/ConfirmSend.vue')['default']
    CorkboardGallery: typeof import('./src/components/CorkboardGallery.vue')['default']
    CountdownIdle: typeof import('./src/components/CountdownIdle.vue')['default']
    IntroModal: typeof import('./src/components/IntroModal.vue')['default']
    PhotoPreview: typeof import('./src/components/PhotoPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShutterAnimation: typeof import('./src/components/ShutterAnimation.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanLoading: typeof import('vant/es')['Loading']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
