/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CameraFrame: typeof import('./src/components/CameraFrame.vue')['default']
    ConfirmSend: typeof import('./src/components/ConfirmSend.vue')['default']
    CorkboardGallery: typeof import('./src/components/CorkboardGallery.vue')['default']
    IntroDialog: typeof import('./src/components/IntroDialog.vue')['default']
    MoyoLoading: typeof import('./src/components/MoyoLoading.vue')['default']
    PhotoPreview: typeof import('./src/components/PhotoPreview.vue')['default']
    QrCode: typeof import('./src/components/QrCode.vue')['default']
    RevealAtField: typeof import('./src/components/RevealAtField.vue')['default']
    RevealCompleteDialog: typeof import('./src/components/RevealCompleteDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShutterAnimation: typeof import('./src/components/ShutterAnimation.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanEmpty: typeof import('vant/es')['Empty']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPickerGroup: typeof import('vant/es')['PickerGroup']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTimePicker: typeof import('vant/es')['TimePicker']
  }
}
